framework: jest
tier: xlarge
postMerge:
  pattern: 
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preMerge:
  pattern:
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preRun:
     command:
        - yarn install
postRun:
     command:
        - yarn --version
version: 2.0
