framework: jest
postMerge:
  pattern: 
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preMerge:
  pattern:
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preRun:
     command:
        - npm install
        - npm install -g pnpm
        - pnpm install --frozen-lockfile --ignore-scripts
postRun:
     command:
        - npm --version
version: 1.1
