framework: jest
postMerge:
  pattern: 
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preMerge:
  pattern:
    - "./test/*.test.js"
    - "./bin/nanoid.test.js"
preRun:
     command:
        - yarn install
        - yarn global add pnpm
        - pnpm install
        - pnpm install --frozen-lockfile --ignore-scripts
postRun:
     command:
        - yarn --version
version: 1.1
